Header header

geometry_msgs/Point         pos_from
geometry_msgs/Vector3       vel_from
geometry_msgs/Vector3       acc_from
geometry_msgs/Quaternion   quat_from
geometry_msgs/Vector3     omega_from
geometry_msgs/Vector3    domega_from

geometry_msgs/Point         pos_to
geometry_msgs/Vector3       vel_to
geometry_msgs/Vector3       acc_to
geometry_msgs/Quaternion   quat_to
geometry_msgs/Vector3     omega_to
geometry_msgs/Vector3    domega_to


